Default: &defaults
  database: Doi.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: Doi_test.sqlite3
  <<: *defaults

Staging:
  database: Doi_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: Doi_production.sqlite3
  poolsize: 100
  <<: *defaults
