Default: &defaults
  user: horus
  password: ""
  host: localhost
  port: 5432
  database: saf
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: logfas_test
  <<: *defaults

Staging:
  database: logfas_staging
  poolsize: 100
  <<: *defaults

Production:
  database: logfas_production
  poolsize: 100
  <<: *defaults
