# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'AwesomeProject' do
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

pod "Ambly", "~> 0.6.0"
end

target 'AwesomeProjectTests' do

end

